### ISSUE TITLE
divide app flow to properly educate about underlying mechanism 

### ISSUE THREAD

**Issue by pociej** [golemfactory/deposit-payment-example#51]
- We work with scenario where each agreement corresponds to a single activity.
- Prior to uploading files, the allocation must be manually created. 
- An activity is generated automatically upon the user uploading a batch of files. 
- Activities have an auto-close timeout displayed to the user.
- Users can upload additional batches of files while an activity is active.
- Users can manually close an activity (and its corresponding agreement), forcing payment for providers release.
- Users can manually close an allocation at any time, enabling fee release.

```[tasklist]
### Tasks
- [x] Expose Allocation from task executor
- [x] Allow task executor to accept allocation as parameter so service can gracefully restart.
- [x] Add UI component for Allocation and agreement management
- [x] Refactor current service code so we have separated methods for allocation creation.
- [x] Extend db models accordingly
```
